language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
  - rbx
before_install:
  - gem install bundler -v 1.12.5

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

install:
  - bundle install

script:
  - bundle exec rubocop
  - bundle exec rake test
